package libgocredentials

import(
	//"crypto"
)

const(
	DEBUG	=  false

	DEFAULT_SALT_LENGTH = 12
	BCRYPT_DEFAULT_COST = 10

	TRANSACTION_READ_UNCOMMITTED	=	"READ UNCOMMITTED"
	TRANSACTION_READ_COMMITTED	=	"READ COMMITTED"
	TRANSACTION_REPEATABLE_READ	=	"REPEATABLE READ"
	TRANSACTION_SERIALIZE		=	"SERIALIZE"
)
